<!DOCTYPE html>
<html lang="iv" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <title>Internal Server Error</title>
        <style>
            body {
    font-family: 'Segoe UI', Tahoma, Arial, Helvetica, sans-serif;
    font-size: .813em;
    color: #222;
    background-color: #fff;
}

h1, h2, h3, h4, h5 {
    /*font-family: 'Segoe UI',Tahoma,Arial,Helvetica,sans-serif;*/
    font-weight: 100;
}

h1 {
    color: #44525e;
    margin: 15px 0 15px 0;
}

h2 {
    margin: 10px 5px 0 0;
}

h3 {
    color: #363636;
    margin: 5px 5px 0 0;
}

code {
    font-family: Consolas, "Courier New", courier, monospace;
}

body .titleerror {
    padding: 3px 3px 6px 3px;
    display: block;
    font-size: 1.5em;
    font-weight: 100;
}

body .location {
    margin: 3px 0 10px 30px;
}

#header {
    font-size: 18px;
    padding: 15px 0;
    border-top: 1px #ddd solid;
    border-bottom: 1px #ddd solid;
    margin-bottom: 0;
}

    #header li {
        display: inline;
        margin: 5px;
        padding: 5px;
        color: #a0a0a0;
        cursor: pointer;
    }

    #header .selected {
        background: #44c5f2;
        color: #fff;
    }

#stackpage ul {
    list-style: none;
    padding-left: 0;
    margin: 0;
    /*border-bottom: 1px #ddd solid;*/
}

#stackpage .details {
    font-size: 1.2em;
    padding: 3px;
    color: #000;
}

#stackpage .stackerror {
    padding: 5px;
    border-bottom: 1px #ddd solid;
}


#stackpage .frame {
    padding: 0;
    margin: 0 0 0 30px;
}

    #stackpage .frame h3 {
        padding: 2px;
        margin: 0;
    }

#stackpage .source {
    padding: 0 0 0 30px;
}

    #stackpage .source ol li {
        font-family: Consolas, "Courier New", courier, monospace;
        white-space: pre;
        background-color: #fbfbfb;
    }

#stackpage .frame .source .highlight li span {
    color: #FF0000;
}

#stackpage .source ol.collapsible li {
    color: #888;
}

    #stackpage .source ol.collapsible li span {
        color: #606060;
    }

.page table {
    border-collapse: separate;
    border-spacing: 0;
    margin: 0 0 20px;
}

.page th {
    vertical-align: bottom;
    padding: 10px 5px 5px 5px;
    font-weight: 400;
    color: #a0a0a0;
    text-align: left;
}

.page td {
    padding: 3px 10px;
}

.page th, .page td {
    border-right: 1px #ddd solid;
    border-bottom: 1px #ddd solid;
    border-left: 1px transparent solid;
    border-top: 1px transparent solid;
    box-sizing: border-box;
}

    .page th:last-child, .page td:last-child {
        border-right: 1px transparent solid;
    }

.page .length {
    text-align: right;
}

a {
    color: #1ba1e2;
    text-decoration: none;
}

    a:hover {
        color: #13709e;
        text-decoration: underline;
    }

.showRawException {
    cursor: pointer;
    color: #44c5f2;
    background-color: transparent;
    font-size: 1.2em;
    text-align: left;
    text-decoration: none;
    display: inline-block;
    border: 0;
    padding: 0;
}

.rawExceptionStackTrace {
    font-size: 1.2em;
}

.rawExceptionBlock {
    border-top: 1px #ddd solid;
    border-bottom: 1px #ddd solid;
}

.showRawExceptionContainer {
    margin-top: 10px;
    margin-bottom: 10px;
}

.expandCollapseButton {
    cursor: pointer;
    float: left;
    height: 16px;
    width: 16px;
    font-size: 10px;
    position: absolute;
    left: 10px;
    background-color: #eee;
    padding: 0;
    border: 0;
    margin: 0;
}

        </style>
    </head>
    <body>
        <h1>An unhandled exception occurred while processing the request.</h1>
            <div class="titleerror">SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint &quot;FK_GalleryEntry_ApplicationUser_AspNetUsers_ApplicationUserID&quot;. The conflict occurred in database &quot;hairydatabase&quot;, table &quot;dbo.AspNetUsers&quot;, column &#x27;Id&#x27;.<br />
The statement has been terminated.</div>
                <p class="location">System.Data.SqlClient.SqlCommand&#x2B;&lt;&gt;c.&lt;ExecuteDbDataReaderAsync&gt;b__107_0(Task&lt;SqlDataReader&gt; result)</p>
            <div class="titleerror">DbUpdateException: An error occurred while updating the entries. See the inner exception for details.</div>
                <p class="location">Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch&#x2B;&lt;ExecuteAsync&gt;d__32.MoveNext()</p>
        <ul id="header">
            <li id="stack" tabindex="1" class="selected">
                Stack
            </li>
            <li id="query" tabindex="2">
                Query
            </li>
            <li id="cookies" tabindex="3">
                Cookies
            </li>
            <li id="headers" tabindex="4">
                Headers
            </li>
        </ul>

        <div id="stackpage" class="page">
            <ul>
                                    <li>
                        <h2 class="stackerror">SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint &quot;FK_GalleryEntry_ApplicationUser_AspNetUsers_ApplicationUserID&quot;. The conflict occurred in database &quot;hairydatabase&quot;, table &quot;dbo.AspNetUsers&quot;, column &#x27;Id&#x27;.&#xA;The statement has been terminated.</h2>
                        <ul>
                            <li class="frame" id="frame1">
                                    <h3>System.Data.SqlClient.SqlCommand&#x2B;&lt;&gt;c.&lt;ExecuteDbDataReaderAsync&gt;b__107_0(Task&lt;SqlDataReader&gt; result)</h3>

                            </li>
                            <li class="frame" id="frame2">
                                    <h3>System.Threading.Tasks.ContinuationResultTaskFromResultTask.InnerInvoke()</h3>

                            </li>
                            <li class="frame" id="frame3">
                                    <h3>System.Threading.Tasks.Task.Execute()</h3>

                            </li>
                            <li class="frame" id="frame4">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame5">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame6">
                                    <h3>Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand&#x2B;&lt;ExecuteAsync&gt;d__26.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame7">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame8">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame9">
                                    <h3>Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch&#x2B;&lt;ExecuteAsync&gt;d__32.MoveNext()</h3>

                            </li>
                        </ul>
                    </li>
                    <li>
                        <br/>
                        <div class="rawExceptionBlock">
                            <div class="showRawExceptionContainer">
                                <button class="showRawException" data-exceptionDetailId="exceptionDetail1">Show raw exception details</button>
                            </div>
                            <div id="exceptionDetail1" class="rawExceptionDetails">
                                <pre class="rawExceptionStackTrace">System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint &quot;FK_GalleryEntry_ApplicationUser_AspNetUsers_ApplicationUserID&quot;. The conflict occurred in database &quot;hairydatabase&quot;, table &quot;dbo.AspNetUsers&quot;, column &#x27;Id&#x27;.&#xA;The statement has been terminated.&#xA;   at System.Data.SqlClient.SqlCommand.&lt;&gt;c.&lt;ExecuteDbDataReaderAsync&gt;b__107_0(Task`1 result)&#xA;   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()&#xA;   at System.Threading.Tasks.Task.Execute()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.&lt;ExecuteAsync&gt;d__26.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.&lt;ExecuteAsync&gt;d__32.MoveNext()&#xA;ClientConnectionId:803ad486-02ba-4fd5-a7e8-c95b6b0d7bb0&#xA;Error Number:547,State:0,Class:16</pre>
                            </div>
                        </div>
                    </li>
                    <li>
                        <h2 class="stackerror">DbUpdateException: An error occurred while updating the entries. See the inner exception for details.</h2>
                        <ul>
                            <li class="frame" id="frame10">
                                    <h3>Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch&#x2B;&lt;ExecuteAsync&gt;d__32.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame11">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame12">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame13">
                                    <h3>Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor&#x2B;&lt;ExecuteAsync&gt;d__10.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame14">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame15">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame16">
                                    <h3>Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy&#x2B;&lt;ExecuteAsync&gt;d__6.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame17">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame18">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame19">
                                    <h3>Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager&#x2B;&lt;SaveChangesAsync&gt;d__54.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame20">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame21">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame22">
                                    <h3>Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager&#x2B;&lt;SaveChangesAsync&gt;d__52.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame23">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame24">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame25">
                                    <h3>Microsoft.EntityFrameworkCore.DbContext&#x2B;&lt;SaveChangesAsync&gt;d__35.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame26">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame27">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame28">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.GetResult()</h3>

                            </li>
                            <li class="frame" id="frame29">
                                    <h3>SparkClips.Controllers.ModelControllers.GalleryEntry_ApplicationUserApiController&#x2B;&lt;PostGalleryEntry_ApplicationUser&gt;d__6.MoveNext() in <code title="/Users/iguest/Desktop/sparkclips/SparkClips/Controllers/ModelControllers/GalleryEntry_ApplicationUserApiController.cs">GalleryEntry_ApplicationUserApiController.cs</code></h3>

                                    <button class="expandCollapseButton" data-frameId="frame29">+</button>
                                    <div class="source">
                                            <ol start="109" class="collapsible">
                                                    <li><span>            {</span></li>
                                                    <li><span>                if (GalleryEntry_ApplicationUserExists(galleryEntry_ApplicationUser.GalleryEntryID))</span></li>
                                                    <li><span>                {</span></li>
                                                    <li><span>                    return new StatusCodeResult(StatusCodes.Status409Conflict);</span></li>
                                                    <li><span>                }</span></li>
                                                    <li><span>                else</span></li>
                                            </ol>

                                        <ol start="115" class="highlight">
                                                <li><span>                {</span></li>
                                        </ol>

                                            <ol start='116' class="collapsible">
                                                    <li><span>                    throw;</span></li>
                                                    <li><span>                }</span></li>
                                                    <li><span>            }</span></li>
                                                    <li><span></span></li>
                                                    <li><span>            return CreatedAtAction(&quot;GetGalleryEntry_ApplicationUser&quot;, new { id = galleryEntry_ApplicationUser.GalleryEntryID }, galleryEntry_ApplicationUser);</span></li>
                                                    <li><span>        }</span></li>
                                            </ol>
                                    </div>
                            </li>
                            <li class="frame" id="frame30">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame31">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame32">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker&#x2B;&lt;InvokeActionMethodAsync&gt;d__27.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame33">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame34">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame35">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker&#x2B;&lt;InvokeNextActionFilterAsync&gt;d__25.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame36">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame37">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)</h3>

                            </li>
                            <li class="frame" id="frame38">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)</h3>

                            </li>
                            <li class="frame" id="frame39">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker&#x2B;&lt;InvokeNextResourceFilter&gt;d__22.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame40">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame41">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)</h3>

                            </li>
                            <li class="frame" id="frame42">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)</h3>

                            </li>
                            <li class="frame" id="frame43">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker&#x2B;&lt;InvokeAsync&gt;d__20.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame44">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame45">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame46">
                                    <h3>Microsoft.AspNetCore.Builder.RouterMiddleware&#x2B;&lt;Invoke&gt;d__4.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame47">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame48">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame49">
                                    <h3>Microsoft.AspNetCore.Authentication.AuthenticationMiddleware&#x2B;&lt;Invoke&gt;d__18.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame50">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame51">
                                    <h3>Microsoft.AspNetCore.Authentication.AuthenticationMiddleware&#x2B;&lt;Invoke&gt;d__18.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame52">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame53">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame54">
                                    <h3>Microsoft.AspNetCore.Authentication.AuthenticationMiddleware&#x2B;&lt;Invoke&gt;d__18.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame55">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame56">
                                    <h3>Microsoft.AspNetCore.Authentication.AuthenticationMiddleware&#x2B;&lt;Invoke&gt;d__18.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame57">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame58">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame59">
                                    <h3>Microsoft.AspNetCore.Authentication.AuthenticationMiddleware&#x2B;&lt;Invoke&gt;d__18.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame60">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame61">
                                    <h3>Microsoft.AspNetCore.Authentication.AuthenticationMiddleware&#x2B;&lt;Invoke&gt;d__18.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame62">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame63">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame64">
                                    <h3>Microsoft.AspNetCore.Authentication.AuthenticationMiddleware&#x2B;&lt;Invoke&gt;d__18.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame65">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame66">
                                    <h3>Microsoft.AspNetCore.Authentication.AuthenticationMiddleware&#x2B;&lt;Invoke&gt;d__18.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame67">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame68">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame69">
                                    <h3>Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware&#x2B;&lt;Invoke&gt;d__5.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame70">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame71">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame72">
                                    <h3>Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware&#x2B;&lt;Invoke&gt;d__6.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame73">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame74">
                                    <h3>Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware&#x2B;&lt;Invoke&gt;d__6.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame75">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame76">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame77">
                                    <h3>Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware&#x2B;&lt;Invoke&gt;d__7.MoveNext()</h3>

                            </li>
                        </ul>
                    </li>
                    <li>
                        <br/>
                        <div class="rawExceptionBlock">
                            <div class="showRawExceptionContainer">
                                <button class="showRawException" data-exceptionDetailId="exceptionDetail2">Show raw exception details</button>
                            </div>
                            <div id="exceptionDetail2" class="rawExceptionDetails">
                                <pre class="rawExceptionStackTrace">Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---&gt; System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint &quot;FK_GalleryEntry_ApplicationUser_AspNetUsers_ApplicationUserID&quot;. The conflict occurred in database &quot;hairydatabase&quot;, table &quot;dbo.AspNetUsers&quot;, column &#x27;Id&#x27;.&#xA;The statement has been terminated.&#xA;   at System.Data.SqlClient.SqlCommand.&lt;&gt;c.&lt;ExecuteDbDataReaderAsync&gt;b__107_0(Task`1 result)&#xA;   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()&#xA;   at System.Threading.Tasks.Task.Execute()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.&lt;ExecuteAsync&gt;d__26.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.&lt;ExecuteAsync&gt;d__32.MoveNext()&#xA;   --- End of inner exception stack trace ---&#xA;   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.&lt;ExecuteAsync&gt;d__32.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.&lt;ExecuteAsync&gt;d__10.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.&lt;ExecuteAsync&gt;d__6`2.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.&lt;SaveChangesAsync&gt;d__54.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.&lt;SaveChangesAsync&gt;d__52.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.EntityFrameworkCore.DbContext.&lt;SaveChangesAsync&gt;d__35.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()&#xA;   at SparkClips.Controllers.ModelControllers.GalleryEntry_ApplicationUserApiController.&lt;PostGalleryEntry_ApplicationUser&gt;d__6.MoveNext() in /Users/iguest/Desktop/sparkclips/SparkClips/Controllers/ModelControllers/GalleryEntry_ApplicationUserApiController.cs:line 115&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.&lt;InvokeActionMethodAsync&gt;d__27.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.&lt;InvokeNextActionFilterAsync&gt;d__25.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.&lt;InvokeNextResourceFilter&gt;d__22.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.&lt;InvokeAsync&gt;d__20.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.AspNetCore.Builder.RouterMiddleware.&lt;Invoke&gt;d__4.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.&lt;Invoke&gt;d__18.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.&lt;Invoke&gt;d__18.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.&lt;Invoke&gt;d__18.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.&lt;Invoke&gt;d__18.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.&lt;Invoke&gt;d__18.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.&lt;Invoke&gt;d__18.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.&lt;Invoke&gt;d__18.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.&lt;Invoke&gt;d__18.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.&lt;Invoke&gt;d__5.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.&lt;Invoke&gt;d__6.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.&lt;Invoke&gt;d__6.MoveNext()&#xA;--- End of stack trace from previous location where exception was thrown ---&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xA;   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.&lt;Invoke&gt;d__7.MoveNext()</pre>
                            </div>
                        </div>
                    </li>
            </ul>
        </div>

        <div id="querypage" class="page">
                <p>No QueryString data.</p>
        </div>

        <div id="cookiespage" class="page">
                <p>No cookie data.</p>
        </div>
        <div id="headerspage" class="page">
                <table>
                    <thead>
                        <tr>
                            <th>Variable</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                                <tr>
                                    <td>Accept</td>
                                    <td>application/json, */*</td>
                                </tr>
                                <tr>
                                    <td>Accept-Encoding</td>
                                    <td>gzip, deflate</td>
                                </tr>
                                <tr>
                                    <td>Connection</td>
                                    <td>keep-alive</td>
                                </tr>
                                <tr>
                                    <td>Content-Length</td>
                                    <td>50</td>
                                </tr>
                                <tr>
                                    <td>Content-Type</td>
                                    <td>application/json</td>
                                </tr>
                                <tr>
                                    <td>Host</td>
                                    <td>localhost:53212</td>
                                </tr>
                                <tr>
                                    <td>User-Agent</td>
                                    <td>HTTPie/0.9.9</td>
                                </tr>
                    </tbody>
                </table>
        </div>
        <script>
            //<!--
            (function (window, undefined) {
    "use strict";

    function ns(selector, element) {
        return new NodeCollection(selector, element);
    }

    function NodeCollection(selector, element) {
        this.items = [];
        element = element || window.document;

        var nodeList;

        if (typeof (selector) === "string") {
            nodeList = element.querySelectorAll(selector);
            for (var i = 0, l = nodeList.length; i < l; i++) {
                this.items.push(nodeList.item(i));
            }
        }
    }

    NodeCollection.prototype = {
        each: function (callback) {
            for (var i = 0, l = this.items.length; i < l; i++) {
                callback(this.items[i], i);
            }
            return this;
        },

        children: function (selector) {
            var children = [];

            this.each(function (el) {
                children = children.concat(ns(selector, el).items);
            });

            return ns(children);
        },

        hide: function () {
            this.each(function (el) {
                el.style.display = "none";
            });

            return this;
        },

        toggle: function () {
            this.each(function (el) {
                el.style.display = el.style.display === "none" ? "" : "none";
            });

            return this;
        },

        show: function () {
            this.each(function (el) {
                el.style.display = "";
            });

            return this;
        },

        addClass: function (className) {
            this.each(function (el) {
                var existingClassName = el.className,
                    classNames;
                if (!existingClassName) {
                    el.className = className;
                } else {
                    classNames = existingClassName.split(" ");
                    if (classNames.indexOf(className) < 0) {
                        el.className = existingClassName + " " + className;
                    }
                }
            });

            return this;
        },

        removeClass: function (className) {
            this.each(function (el) {
                var existingClassName = el.className,
                    classNames, index;
                if (existingClassName === className) {
                    el.className = "";
                } else if (existingClassName) {
                    classNames = existingClassName.split(" ");
                    index = classNames.indexOf(className);
                    if (index > 0) {
                        classNames.splice(index, 1);
                        el.className = classNames.join(" ");
                    }
                }
            });

            return this;
        },

        attr: function (name) {
            if (this.items.length === 0) {
                return null;
            }

            return this.items[0].getAttribute(name);
        },

        on: function (eventName, handler) {
            this.each(function (el, idx) {
                var callback = function (e) {
                    e = e || window.event;
                    if (!e.which && e.keyCode) {
                        e.which = e.keyCode; // Normalize IE8 key events
                    }
                    handler.apply(el, [e]);
                };

                if (el.addEventListener) { // DOM Events
                    el.addEventListener(eventName, callback, false);
                } else if (el.attachEvent) { // IE8 events
                    el.attachEvent("on" + eventName, callback);
                } else {
                    el["on" + type] = callback;
                }
            });

            return this;
        },

        click: function (handler) {
            return this.on("click", handler);
        },

        keypress: function (handler) {
            return this.on("keypress", handler);
        }
    };

    function frame(el) {
        ns(".source .collapsible", el).toggle();
    }

    function expandCollapseButton(el) {
        var frameId = el.getAttribute("data-frameId");
        frame(document.getElementById(frameId));
        if (el.innerText === "+") {
            el.innerText = "-";
        }
        else {
            el.innerText = "+";
        }
    }

    function tab(el) {
        var unselected = ns("#header .selected").removeClass("selected").attr("id");
        var selected = ns("#" + el.id).addClass("selected").attr("id");

        ns("#" + unselected + "page").hide();
        ns("#" + selected + "page").show();
    }

    ns(".rawExceptionDetails").hide();
    ns(".collapsible").hide();
    ns(".page").hide();
    ns("#stackpage").show();

    ns(".expandCollapseButton")
        .click(function () {
            expandCollapseButton(this);
        })
        .keypress(function (e) {
            if (e.which === 13) {
                expandCollapseButton(this);
            }
        });

    ns("#header li")
        .click(function () {
            tab(this);
        })
        .keypress(function (e) {
            if (e.which === 13) {
                tab(this);
            }
        });

    ns(".showRawException")
        .click(function () {
            var exceptionDetailId = this.getAttribute("data-exceptionDetailId");
            ns("#" + exceptionDetailId).toggle();
        });
})(window);
            //-->
        </script>
    </body>
</html>
